### ISSUE TITLE
VSCode extension not working

### ISSUE THREAD

**Issue by santiagolator** [EdisonLabs-Inc/CodeViz-Public#1]
Hi team, just to let you know that the extension is not working for me. The codeviz's extension screen goes blank, sometimes after giving a glimpse of content. I have a python project opened.

![screen_codeviz_vscode](https://github.com/user-attachments/assets/47acd1b0-5d52-4bed-bba9-a256ee14fece)

My VSCode:
![Captura de pantalla 2024-08-17 114400](https://github.com/user-attachments/assets/87ecba0f-6995-4846-a775-d437e7a66120)

**Comment by liam-prevelige** [comment]
Thanks for the report, are you using v1.2.21? Latest update fixes an issue related to non default color schemes

**Comment by santiagolator** [comment]
Updated itself and it's working correctly now! Thanks!

**Comment by liam-prevelige** [comment]
Great!
