### ISSUE TITLE
Display pricing on the website

### ISSUE THREAD

**Issue by mrprkr** [EdisonLabs-Inc/CodeViz-Public#6]
Extension throws an error on installation
Clicking the error is the only way to access pricing
Pricing is displayed with no context of what that is for

**Comment by liam-prevelige** [comment]
High priority, thank you. #8 captures this too.

Are you using v1.3.31? You shouldn't receive an error on installation with the latest version of CodeViz. VS Code extension updates can be inconsistent. This is significantly worse if you're using Cursor, as it often lags behind VS Code by several days
